spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yzx
    username: root
    password: root

  session:
    timeout: 86400

server:
  address: 0.0.0.0